import type { Metadata } from "next";

import "../globals.css";
import { ThemeProvider } from "@/components/ThemeProvider";
import {
    SidebarProvider,
    SidebarTrigger,
    SidebarInset,
} from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/AppSidebar";
import { Toaster } from "@/components/ui/sonner";
import { fetchSiteLabels } from "@/lib/fetchSiteLabels";



export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    // Busque os labels do Strapi
    const labels = await fetchSiteLabels();

    return (
       
           
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <SidebarProvider>
                        <AppSidebar labels={labels} />
                        <SidebarInset>
                            <header className="flex h-16 shrink-0 items-center gap-2 transition-[width,height] ease-linear group-has-data-[collapsible=icon]/sidebar-wrapper:h-12">
                                <div className="flex items-center gap-2 px-4">
                                    <SidebarTrigger className="-ml-1" />
                                    <div className="h-6 w-px bg-border mx-2" />
                                    <h1 className="text-lg font-semibold">
                                        {labels.headerTitle || "Agente ITFolks"}
                                    </h1>
                                </div>
                            </header>
                            <div className="flex flex-1 flex-col gap-4 p-4 pt-0">
                                {children}
                            </div>
                        </SidebarInset>
                    </SidebarProvider>
                    <Toaster position="top-right" expand={true} richColors closeButton />
                </ThemeProvider>
            
        
    );
}
